[package]
name = "engula-kernel"
version = "0.2.0"
edition = "2021"

[dependencies]
engula-journal = { package = "journal", path = "../journal" }
engula-storage = { package = "storage", path = "../storage" }

async-trait = "0.1"
futures = "0.3"
