# Copyright 2021 The Engula Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: '3'
services:
  journal:
    image: ghcr.io/tisonkun/engula:nightly
    ports:
      - "10001:10001"
      - "10002:10002"
      - "10003:10003"
    command: journal run 0.0.0.0:10001 --mem
  storage:
    image: ghcr.io/tisonkun/engula:nightly
    network_mode: "service:journal"
    depends_on:
      - journal
    command: storage run 0.0.0.0:10002 --mem
  kernel:
    image: ghcr.io/tisonkun/engula:nightly
    network_mode: "service:journal"
    depends_on:
      - journal
      - storage
    command: kernel run 0.0.0.0:10003 --journal 0.0.0.0:10001 --storage 0.0.0.0:10002 --mem

