[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[tasks.fmt-check]
command = "cargo"
args = ["fmt", "--all", "--", "--check"]

[tasks.clippy]
command = "cargo"
args = ["clippy", "--workspace", "--tests", "--all-features", "--", "-D", "warnings"]

[tasks.build]
command = "cargo"
args = ["build"]

[tasks.test]
command = "cargo"
args = ["test", "--workspace"]

[tasks.audit]
command = "cargo"
args = ["audit"]

[tasks.udeps]
command = "cargo"
args = ["udeps", "--workspace"]

[tasks.lint]
dependencies = [
    "fmt-check",
    "clippy"
]

[tasks.deps-check]
dependencies = [
    "audit",
    "udeps"
]

[tasks.workflow]
dependencies = [
    "lint",
    "deps-check",
    "build",
    "test",
]
