// Copyright 2022 The Engula Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

pub const PAGE_SIZE: usize = 4096;
pub const MAX_BLOCK_SIZE: usize = 1024 * 32;

// +----------+-----------------+-----------+-------- -+--- ... ---+
// |Type (1B) | Log number (1B) | Size (2B) | CRC (4B) | Payload   |
// +----------+-----------------+-----------+----------+--- ... ---+
pub const RECORD_HEADER_SIZE: usize = 8;

/// Indicates start here, entire range are empty until the end of block. This is
/// usually generated by `[preallocate`].
pub const RECORD_EMPTY: u8 = 0;
/// Indicates there is a trailing physical record, and only contains the header
/// of record.
pub const RECORD_HEAD: u8 = 1;
/// Indicates there is a middle content of a record.
pub const RECORD_MID: u8 = 2;
/// Indicates there is a tail content of a record.
pub const RECORD_TAIL: u8 = 3;
/// Indicates the physical record contains entire content of a record.
pub const RECORD_FULL: u8 = 4;
/// Indicates there exists a record which content is always zero, it is
/// generated by aligining the old record or skipping avail space.
pub const RECORD_ZERO: u8 = 5;
/// Indicates there exists a empty range until the next page boundary.
pub const RECORD_PAGE_ALIGN: u8 = 6;

pub const RECORD_BAD_LENGTH: u8 = 253;
pub const RECORD_BAD_CRC32: u8 = 254;
