[package]
name = "engula-hash-engine"
version = "0.2.0"
edition = "2021"

[dependencies]
engula-kernel = { path = "../../kernel" }
engula-journal = { path = "../../journal" }
engula-storage = { path = "../../storage" }

thiserror = "1.0"
tokio = { version = "1.14", features = ["full"] }
bytes = "1.1"
futures = "0.3"
