[package]
name = "object-engine-lsmstore"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
object-engine-common = { path = "../common" }
object-engine-filestore = { path = "../filestore" }

bytes = "1.1"
