# Copyright 2022 The Engula Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Enhancement
description: Enhance code, document, and more
labels: [ "enhancement" ]
body:
  - type: markdown
    attributes:
      value: |
        Thank you very much for your enhancement for Engula!
  - type: checkboxes
    attributes:
      label: Search before asking
      description: >
        Please search in the [issues](https://github.com/engula/engula/issues) first to see whether the same issue has been reported before.
      options:
        - label: >
            I had searched in the [issues](https://github.com/engula/engula/issues) and found no similar issues.
          required: true
  - type: textarea
    attributes:
      label: Motivation
      description: Describe the motivation you'd like to make this enhancement.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Solution
      description: Describe the proposed solution and add related materials like links if any.
  - type: checkboxes
    attributes:
      label: Are you willing to submit a PR?
      description: >
        We very much look forward for your help to improve Engula together. If you are willing to submit a PR for this enhancement, please tick it.
      options:
        - label: I'm willing to submit a PR!
  - type: markdown
    attributes:
      value: "Thanks for completing our form!"
