[package]
name = "stream-engine-proto"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
stream-engine-common = { version = "0.1", path = "../common" }

prost = "0.9"
tonic = "0.6"

[build-dependencies]
tonic-build = "0.6"
