[package]
name = "engula-engine"
version = "0.3.0"
edition = "2021"
license = "Apache-2.0"
homepage = "https://engula.io"
repository = "https://github.com/engula/engula"
description = "The Engula server."

[dependencies]
bytes = "1.0"

[dev-dependencies]
criterion = "0.3"
criterion-macro = "0.3"
rand = "0.8.5"

[[bench]]
name = "engine_bench"
