# The listening address of the current node.
# Default: "127.0.0.1:21805"
addr = "127.0.0.1:21805"

# Whether the cluster needs to be initialized.
# Default: false
init = false

# A list of existing members of the cluster. This option only takes effect when
# `init` is false.
join_list = []

root_dir = "/tmp/engula"

# Whether to allow the current node to serve as Engula's proxy service.
# Default: false
enable_proxy_service = false

# The num of cpu cores this engula node is allowed to use, engula will assign a
# worker thread to each core. If set to 0 , then engula automatically detects
# and sets the value to the number of cores of the local CPU.
# Default: 0
cpu_nums = 0

[node]
shard_chunk_size = 67108864
shard_gc_keys = 256

[node.replica]
snap_file_size = 68719476736

[raft]
election_tick = 3
max_inflight_msgs = 10000
max_inflight_requests = 102400
max_size_per_msg = 67108864
tick_interval_ms = 500

[root]
enable_group_balance = true
enable_replica_balance = true
enable_shard_balance = true
heartbeat_timeout_sec = 4
liveness_threshold_sec = 30
max_create_group_retry_before_rollback = 10
replicas_per_group = 3
schedule_interval_sec = 1

[executor]
event_interval = 31
global_event_interval = 31
