# Copyright 2022 Engula Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: '25 4 * * *'

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  license:
    if: (github.event_name == 'schedule' && github.repository == 'engula/engula') || (github.event_name != 'schedule')
    name: Check license header
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: apache/skywalking-eyes@main
        with:
          config: tools/ci/licenserc.yml

  test:
    if: (github.event_name == 'schedule' && github.repository == 'engula/engula') || (github.event_name != 'schedule')
    name: Run tests

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v1
      - name: Cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
      - name: Verify tidy
        run: git diff --exit-code
      - name: Check clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --workspace --tests --all-features -- -D warnings
      - name: Check format
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      - name: Cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --workspace
