[package]
name = "storage"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
bytes = "1.1"
thiserror = "1.0"
async-trait = "0.1"
futures = "0.3"
tokio = { version = "1.13", features = ["full"] }
