[package]
name = "storage"
version = "0.2.0"
edition = "2021"
publish = false

[dependencies]
thiserror = "1.0"
async-trait = "0.1"
futures = "0.3"
tokio = { version = "1.13", features = ["full"] }
tonic = "0.6"
prost = "0.9"

[build-dependencies]
tonic-build = "0.6"