[package]
name = "engula-storage"
version = "0.2.0"
edition = "2021"
license = "Apache-2.0"
homepage = "https://engula.io"
repository = "https://github.com/engula/engula"
description = "A data object storage module for Engula."

[dependencies]
thiserror = "1.0"
async-trait = "0.1"
bytes = "1.1.0"
tokio = { version = "1.13", features = ["full"] }

[build-dependencies]
tonic-build = "0.6"
