[package]
name = "storage"
version = "0.1.0"
edition = "2021"
publish = false

[features]

default = [ "aws-s3" ]

full = [ "aws-s3" ]

aws-s3 = [ "aws-types", "aws-sdk-s3"]

[dependencies]
async-trait = "0.1"
aws-types = { git = "https://github.com/awslabs/aws-sdk-rust", tag = "v0.0.17-alpha", package = "aws-types", optional = true }
aws-sdk-s3 = { git = "https://github.com/awslabs/aws-sdk-rust", tag = "v0.0.17-alpha", package = "aws-sdk-s3", optional = true }
bytes = "1.1"
thiserror = "1.0"
tokio = { version = "1.13.0", features = ["full"] }