[package]
name = "engula-journal"
version = "0.2.0"
edition = "2021"

[dependencies]
thiserror = "1.0"
async-trait = "0.1"
futures = "0.3"
tokio = { version = "1.13", features = ["full"] }
tokio-stream = { version = "0.1", features = ["net"] }
tonic = "0.6"
prost = "0.9"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[build-dependencies]
tonic-build = "0.6"
