[package]
name = "engula-common"
version = "0.3.0"
edition = "2021"
license = "Apache-2.0"
homepage = "https://engula.io"
repository = "https://github.com/engula/engula"
description = "The common crate for Engula."

[dependencies]
thiserror = "1.0"
tonic = "0.6"
