[package]
name = "engula-client"
version = "0.4.0"
edition = "2021"
license = "Apache-2.0"
homepage = "https://engula.io"
repository = "https://github.com/engula/engula"
description = "The Engula API."

[dependencies]
engula-api = { version = "0.4", path = "../api" }
prost = "0.10.3"
thiserror = "1.0.31"
tokio = { version = "1.18.2", features = ["full"] }
tokio-stream = { version = "0.1.8", features = ["net"] }
tonic = "0.7.2"
tracing = "0.1"
crc32fast = "1.3.2"

[dev-dependencies]
tracing-subscriber = { version = "0.3", features = ["std", "env-filter"] }
