[package]
name = "engula-client"
version = "0.4.0"
edition = "2021"
license = "Apache-2.0"
homepage = "https://engula.io"
repository = "https://github.com/engula/engula"
description = "The Engula API."

[dependencies]
engula-api = { version = "0.4", path = "../api" }
tonic = "0.7.2"
