[package]
name = "engula-client"
version = "0.3.0"
edition = "2021"
license = "Apache-2.0"
homepage = "https://engula.io"
repository = "https://github.com/engula/engula"
description = "The Rust client for Engula."

[dependencies]
engula-apis = { version = "0.3", path = "../apis" }
prost = "0.9"
thiserror = "1.0"
tokio = { version = "1.15", features = ["full"] }
tonic = "0.6"

[dev-dependencies]
anyhow = "1.0"
