[package]
name = "engula-bench"
version = "0.4.0"
edition = "2021"
license = "Apache-2.0"
homepage = "https://engula.io"
repository = "https://github.com/engula/engula"
description = "The bench tools for engula"

[dependencies]
engula-client = { path = "../../client", version = "0.4.0" }
engula-server = { path = "../../server", version = "0.4.0" }

atty = "0.2.14"
clap = { version = "3.2.20", features = ["derive"] }
config = { version = "0.13.2", features = ["toml"] }
lazy_static = "1.4.0"
num_cpus = "1.13.1"
paste = "1.0"
prometheus = "0.13.2"
rand = { version = "0.8.5", features = ["small_rng"] }
serde = { version = "1.0.144", features = ["derive"] }
tokio = { version = "1.21.0", features = ["full"] }
toml = { version = "0.5" }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["std", "env-filter"] }
