# Copyright 2021 The Engula Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: '25 4 * * *'

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  license:
    if: (github.event_name == 'schedule' && github.repository == 'engula/engula') || (github.event_name != 'schedule')
    name: Check license header
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: apache/skywalking-eyes@main
        with:
          config: tools/ci/licenserc.yml

  editorconfig:
    if: (github.event_name == 'schedule' && github.repository == 'engula/engula') || (github.event_name != 'schedule')
    name: Check editorconfig
    needs: [license]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: editorconfig-checker/editorconfig-checker
          path: editorconfig-checker
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - run: |
          pushd editorconfig-checker && make build && popd && \
          editorconfig-checker/bin/ec -exclude editorconfig-checker

  toml:
    if: (github.event_name == 'schedule' && github.repository == 'engula/engula') || (github.event_name != 'schedule')
    name: Check TOML
    needs: [editorconfig]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check Skip CI
        id: skip-ci
        uses: ./.github/actions/skip
        with:
          paths-ignore: >-
            "*"
          paths: >-
            "*.toml"
      - name: Install taplo-cli
        if: steps.skip-ci.outputs.skip != 'true'
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: taplo-cli
      - name: Check TOML
        if: steps.skip-ci.outputs.skip != 'true'
        run: taplo format --check

  dependency:
    if: (github.event_name == 'schedule' && github.repository == 'engula/engula') || (github.event_name != 'schedule')
    name: Check dependency
    needs: [editorconfig]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check Skip CI
        id: skip-ci
        uses: ./.github/actions/skip
        with:
          paths-ignore: >-
            "*"
          paths: >-
            "Cargo.lock"
      - name: Install cargo-udeps
        if: steps.skip-ci.outputs.skip != 'true'
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-udeps --locked
      - name: Check udeps
        if: steps.skip-ci.outputs.skip != 'true'
        uses: actions-rs/cargo@v1
        with:
          command: udeps
          args: --workspace

  security:
    if: (github.event_name == 'schedule' && github.repository == 'engula/engula') || (github.event_name != 'schedule')
    name: Audit security
    needs: [editorconfig]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check Skip CI
        id: skip-ci
        uses: ./.github/actions/skip
        with:
          paths-ignore: >-
            "*"
          paths: >-
            "Cargo.lock"
      - name: Install cargo-aduit
        if: steps.skip-ci.outputs.skip != 'true'
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-audit
      - name: Audit dependencies
        if: steps.skip-ci.outputs.skip != 'true'
        uses: actions-rs/cargo@v1
        with:
          command: audit

  test:
    if: (github.event_name == 'schedule' && github.repository == 'engula/engula') || (github.event_name != 'schedule')
    name: Run tests
    needs: [editorconfig]
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        rust: [nightly]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Check Skip CI
      id: skip-ci
      uses: ./.github/actions/skip

    - name: Install Rust toolchain
      if: steps.skip-ci.outputs.skip != 'true'
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.rust }}
        components: clippy, rustfmt
        override: true

    - uses: Swatinem/rust-cache@v1
      if: steps.skip-ci.outputs.skip != 'true'

    - name: Cargo build
      if: steps.skip-ci.outputs.skip != 'true'
      uses: actions-rs/cargo@v1
      with:
        command: build

    - name: Verify tidy
      if: steps.skip-ci.outputs.skip != 'true'
      run: git diff --exit-code

    - name: Check clippy
      if: steps.skip-ci.outputs.skip != 'true'
      uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: --workspace --tests --all-features -- -D warnings

    - name: Check format
      if: steps.skip-ci.outputs.skip != 'true'
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: --all -- --check

    - name: Cargo test
      if: steps.skip-ci.outputs.skip != 'true'
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --workspace

  pass:
    name: All tests passed
    runs-on: ubuntu-latest
    needs:
      - toml
      - dependency
      - security
      - test
    steps:
      - run: exit 0
