# Copyright 2021 The Engula Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: S3 Integration Tests

on:
  push:
    paths:
      - 'platform/aws/'
  pull_request:
    paths:
      - 'platform/aws/'

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  minio:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
        components: rustfmt
        override: true

    - name: Cargo build
      uses: actions-rs/cargo@v1
      with:
        command: build

    - name: Setup minio
      run: |
        docker run --detach \
          -p 9000:9000 \
          -p 9001:9001 \
          -v "$(mktemp -d)":/data \
          -e "MINIO_ROOT_USER=engulatest" \
          -e "MINIO_ROOT_PASSWORD=engulatest" \
          -e "MINIO_REGION_NAME=us-east-2" \
          quay.io/minio/minio server /data --console-address ":9001"

    - name: Liveness probe
      timeout-minutes: 1
      run: |
        until curl http://127.0.0.1:9000/minio/health/live; do
            sleep 1
        done

    - name: Cargo test
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --manifest-path src/platform/aws/Cargo.toml integration_test_ -- --ignored
